# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3e1acf141bb1d0387bf838306c25f7f27adf142a4b380fe4f3bf48a30a0c3897a27bfceb706fb160beaf7af7e3c540400a00c7288fd44a3a820c7319df2cd3c

test:
  secret_key_base: e50934903c6b6b048bbc2b5af2f964bcbb41fedc50325e9fb641b24e2aa3f5acaafdd2fb58b5d0c8565fe492b842ee7d8ad1602fb28c45a2e9d7a9a167de2b46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
